apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-proxy
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-proxy
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/status", "endpoints", "services", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-proxy
subjects:
  - kind: ServiceAccount
    name: kube-proxy
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy
  template:
    metadata:
      labels:
        k8s-app: kube-proxy
    spec:
      hostNetwork: true
      serviceAccountName: kube-proxy
      containers:
        - name: kube-proxy
          image: registry.k8s.io/kube-proxy:v1.28.1
          command:
            - /usr/local/bin/kube-proxy
            - --v=2
            - --config=/var/lib/kube-proxy/config.conf
          volumeMounts:
            - mountPath: /var/lib/kube-proxy
              name: kube-proxy
      volumes:
        - name: kube-proxy
          hostPath:
            path: /var/lib/kube-proxy
