apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: delaparra-cloud
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 13.9.5
  values:
    global:
      postgresql:
        postgresqlDatabase: delaparra-cloud
        postgresqlUsername: reinier
        postgresqlPassword: asdasd
    primary:
      persistence:
        enabled: true
        size: 8Gi
